### ISSUE TITLE
Broken Whirlpool

### ISSUE THREAD

**Issue by wkdkristina** [plaza-in-a-heatwave/Obsidio-Server#15]
Broken corner of whirlpool during cadesim

![broken whirlpool](https://user-images.githubusercontent.com/57062087/68257424-34dbaa80-0001-11ea-9900-4219c032423e.png)

**Comment by plaza-in-a-heatwave** [comment]
This looks like an error in map file Loggerhead_XXIX_Round_5 - line 12
