### ISSUE TITLE
proposal/vote for kick

### ISSUE THREAD

**Issue by wkdkristina** [plaza-in-a-heatwave/Obsidio-Server#29]
when someone either DC's or basically falls asleep should be able to vote them out - not with 100% vote - but 1 less

**Comment by plaza-in-a-heatwave** [comment]
It's hard to strike a balance - the vote is configurable (set to 75% on current server), but if it goes too low a whole team could kick another team. e.g. at 50% 1v1s will be able to kick each other.

Perhaps the server could find players who haven't responded (e.g. sleep/lag) and make them not eligible for voting?

**Comment by plaza-in-a-heatwave** [comment]
It's hard to strike a balance - the vote is configurable (set to 75% on current server), but if it goes too low a whole team could kick another team. e.g. at 50% 1v1s will be able to kick each other.

Perhaps the server could find players who haven't responded (e.g. sleep/lag) and make them not eligible for voting?

**Comment by plaza-in-a-heatwave** [comment]
Closing as covered by server commandline config already
