### ISSUE TITLE
Player gets extra move before sinking

### ISSUE THREAD

**Issue by plaza-in-a-heatwave** [plaza-in-a-heatwave/Obsidio-Server#66]
Two severely damaged ships shoot at each other. They should sink at the same time, but one gets to fire an additional round of cannons (or perform a final move?) before sinking.

Apparently this only happens to the defender.

![def_sink_bg](https://user-images.githubusercontent.com/36822438/91499449-558b2e80-e8b9-11ea-8094-df704cb505a2.gif)

**Comment by David52920** [comment]
For loop is being run twice when all vessels are sinking, one of the vessel isn’t null at the same time as the others which causes a delay
